name: Build geoip files
on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"
  push:
    branches:
      - master
    paths-ignore:
      - ".gitignore"
      - "config-example.json"
      - "LICENSE"
      - "README.md"
      - ".github/dependabot.yml"
      - ".github/workflows/delete-old-workflows.yml"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true
          repo: DustinWin/clash-geoip

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: ./go.mod

      - name: Set variables
        run: |
          echo "RELEASE_NAME=latest" >> $GITHUB_ENV
          echo "netflixip=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix_IP.txt" >> $GITHUB_ENV
          echo "telegramip=https://core.telegram.org/resources/cidr.txt" >> $GITHUB_ENV
          echo "lanip=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml" >> $GITHUB_ENV
          echo "cn1=https://raw.githubusercontent.com/17mon/china_ip_list/master/china_ip_list.txt" >> $GITHUB_ENV
          echo "cn2=https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china.txt" >> $GITHUB_ENV
          echo "cn3=https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMax/ChinaMax_IP.txt" >> $GITHUB_ENV
          echo "cn4=https://raw.githubusercontent.com/gaoyifan/china-operator-ip/ip-lists/china6.txt" >> $GITHUB_ENV
        shell: bash

      - name: Fetch lists from ripe.net
        run: |
          chmod +x asn.sh
          ./asn.sh

      - name: Generate netflixip
        run: |
          mkdir -p ./tmp ./publish
          curl -sSL ${netflixip} | grep -v '#' | sed '/^\s*$/d' > data/netflixip

      - name: Generate telegramip
        run: |
          curl -sSL ${telegramip} > data/telegramip

      - name: Generate lanip
        run: |
          curl -sSL ${lanip} | grep 'IP-CIDR' | grep -v '#' | sed 's/.*,//g' | sed '/^\s*$/d' > data/lanip

      - name: Generate cn
        run: |
          curl -sSL ${cn1} > ./tmp/temp-cn.txt
          curl -sSL ${cn2} >> ./tmp/temp-cn.txt
          curl -sSL ${cn3} | grep -v '#\|^::' | sed '/^\s*$/d' >> ./tmp/temp-cn.txt
          curl -sSL ${cn4} >> ./tmp/temp-cn.txt
          sort --ignore-case -u ./tmp/temp-cn.txt > data/cn

      - name: Build geoip files
        run: |
          go run ./

      - name: Verify mmdb files
        run: |
          cd ./output/maxmind || exit 1
          go install -v github.com/maxmind/mmdbverify@latest
          for name in $(ls *.mmdb); do
            $(go env GOPATH)/bin/mmdbverify -file ${name}
          done

      - name: Move files to publish directory
        run: |
          mv -f ./output/dat/*.dat ./output/maxmind/*.mmdb ./publish
          cp -f ./output/text ./publish

      - name: Git push assets to "release" branch
        run: |
          cd ./publish || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add geoip "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u geoip release

      - name: Purge jsDelivr CDN
        run: |
          cd ./publish || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/${{ github.repository }}@release/${file}"
          done

      - name: Remove text
        run: |
          rm -rf ./publish/text

      - name: Release and upload assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          release_name: latest
          tag: latest
          file_glob: true
          file: ./publish/*
